name: Build deb packages

on:
  push:

jobs:
  builder:
    name: 'Build .deb package'
    strategy:
      fail-fast: false
      matrix:
        os: ['debian11', 'ubuntu20.04', 'ubuntu22.04']
    runs-on: ubuntu-latest
    container:
      image: openroad/${{ matrix.os }}-dev

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: true

      - name: Set release version
        id: set_version
        run: |
          git config --global --add safe.directory '*'
          echo "RELEASE_VERSION=$(git describe | sed 's/v//')" >> $GITHUB_ENV
          echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build package
        run: |
          ./debian/create-changelog.sh ${{ env.RELEASE_VERSION }}
          debuild --preserve-env --preserve-envvar=PATH -B
          # move files because upload-artifacts do not allow relative paths
          mv ../openroad*.deb .

      - name: Upload workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: openroad_${{ env.RELEASE_VERSION }}_${{ matrix.os }}_amd64.deb
          path: openroad_${{ env.RELEASE_VERSION }}_amd64.deb

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: builder
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release if not exists
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          body: |
            "Release ${{ env.RELEASE_VERSION }} on ${{ env.RELEASE_DATE }}"

  upload_release_assets:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    needs: [builder, create_release]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Upload debian11 Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/openroad_${{ env.RELEASE_VERSION }}_debian11_amd64.deb
          asset_name: openroad_${{ env.RELEASE_VERSION }}_debian11_amd64.deb
          asset_content_type: application/octet-stream

      - name: Upload ubuntu20.04 Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/openroad_${{ env.RELEASE_VERSION }}_ubuntu20.04_amd64.deb
          asset_name: openroad_${{ env.RELEASE_VERSION }}_ubuntu20.04_amd64.deb
          asset_content_type: application/octet-stream

      - name: Upload ubuntu22.04 Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/openroad_${{ env.RELEASE_VERSION }}_ubuntu22.04_amd64.deb
          asset_name: openroad_${{ env.RELEASE_VERSION }}_ubuntu22.04_amd64.deb
          asset_content_type: application/octet-stream
