name: Build deb packages

on:
  push:

jobs:

  get_version:
    name: 'Set Release Version'
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.set_version.outputs.date }}
      version: ${{ steps.set_version.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set release version
        id: set_version
        run: |
          git config --global --add safe.directory '*'
          echo "version=$(git describe | sed 's/v//')" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

  builder:
    name: 'Build .deb package'
    needs: get_version
    strategy:
      fail-fast: false
      matrix:
        os: ['debian11', 'ubuntu20.04', 'ubuntu22.04']
    runs-on: ubuntu-latest
    container:
      image: openroad/${{ matrix.os }}-dev

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set safe directory
        run: |
          git config --global --add safe.directory '*'

      - name: Build package
        run: |
          ./debian/create-changelog.sh ${{ needs.get_version.outputs.version }}
          debuild --preserve-env --preserve-envvar=PATH -B
          # move files because upload-artifacts do not allow relative paths
          mv ../openroad*${{ needs.get_version.outputs.version }}* .

      - name: Upload workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: openroad_${{ needs.get_version.outputs.version }}_${{ matrix.os }}_amd64.deb
          path: openroad_${{ needs.get_version.outputs.version }}_amd64.deb

  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [get_version, builder]
    steps:

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            "Release ${{ needs.get_version.outputs.version }} on ${{ needs.get_version.outputs.date }}"
          name: ${{ needs.get_version.outputs.version }}
          tag_name: ${{ needs.get_version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            artifacts/openroad_${{ needs.get_version.outputs.version }}_debian11_amd64.deb
            artifacts/openroad_${{ needs.get_version.outputs.version }}_ubuntu20.04_amd64.deb
            artifacts/openroad_${{ needs.get_version.outputs.version }}_ubuntu22.04_amd64.deb
